### PR TITLE
Some cmake logic to get us started

### PR DESCRIPTION
**Pull request by frankmiller**
This is a simple cmake project that utilizes FetchContent to get the internal `example` project and the external `scnlib` project, build them both, and link them into a simple "test".

### CODE REVIEW

**Comment by rmpowell77** [comment]
Should this be put into the `example` git repository?

**Comment by frankmiller** [comment]
> Should this be put into the example git repository?

The intention for this is to be a meta-build that brings in all beman libraries thus it needs to be outside of the example repository. I could be moved to a different independent repository but I think it makes sense for this to be here and I believe @camio voiced agreement in our last Friday morning in person meeting.

**Comment by frankmiller** [comment]
FYI: https://github.com/eliaskosunen/scnlib/pull/113

**Comment by rmpowell77** [comment]
> Should this be put into the `example` git repository?

Asked and answered in the Thursday discussion.  Resolved!

**Review by bretbrownjr — APPROVED** [review]
This has been hanging out for a week. I'm going to merge with the understanding that this approach is still up for reconsideration. But I have talked to a few people offline since this PR went up about how to "join" the Beman Project, and adding some more `FetchContent` logic for compatible repos seems to be the most accessible approach right now.

In short, I like this starting point.

**Pull request merged**
